[entryPoints]
  [entryPoints.web]
    address = ":{{ traefik_port_http }}"

  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"

  [entryPoints.websecure]
    address = ":{{ traefik_port_https }}"

      [entryPoints.websecure.http.tls]
        certResolver = "cloudflare"

        [entryPoints.websecure.http.tls.domains]
          main = "{{ ansible_nas_domain }}"
          sans = [
            "*.{{ ansible_nas_domain }}"
          ]

  [entryPoints.traefik]
    address = ":{{ traefik_port_ui }}"


[http.middlewares.admin-auth.basicAuth]
  users = [
    "{{ traefik_web_user }}:{{ traefik_web_password }}"
  ]

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    exposedbydefault = false

[api]
  insecure = true
  dashboard = true

[log]
  level = "{{ traefik_log_level }}"

[ping]
  terminatingStatusCode = 0

[certificatesResolvers]
  [certificatesResolvers.cloudflare]
    [certificatesResolvers.cloudflare.acme]
      email = "{{ ansible_nas_email }}"
      storage = "/letsencrypt/acme.json"

      [certificatesResolvers.cloudflare.acme.dnsChallenge]
        provider = "{{ traefik_dns_provider }}"
        delaybeforecheck = "0"
        resolvers = "1.1.1.1:53,1.0.0.1:53"        
