---
- name: Create pihole Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ pihole_config_directory }}"
    - "{{ pihole_dnsmasq_directory }}"

- name: pihole Docker Container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    pull: true
    volumes:
      - '{{ pihole_config_directory }}:/etc/pihole/'
      - '{{ pihole_dnsmasq_directory }}:/etc/dnsmasq.d/'
    ports:
      - "{{ pihole_port_http }}:80"
      - "53:53"
      - "53:53/udp"
      - "67:67/udp"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      WEBPASSWORD: "{{ pihole_password }}"
      PIHOLE_DNS_: "8.8.8.8;8.8.4.4"
      VIRTUAL_HOST: "{{ pihole_hostname }}.{{ ansible_nas_domain }}"
    restart_policy: unless-stopped
    memory: "{{ pihole_memory }}"
    labels:
      traefik.enable: "{{ pihole_available_externally }}"
      traefik.http.routers.pihole.rule: "Host(`{{ pihole_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.pihole.tls.certresolver: "cloudflare"
      traefik.http.routers.pihole.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.pihole.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.pihole.loadbalancer.server.port: "80"